components:
  schemas:
    Body_create_upload_file_ocr_pdf_post:
      properties:
        file:
          format: binary
          title: File
          type: string
      required:
      - file
      title: Body_create_upload_file_ocr_pdf_post
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.0.2
paths:
  /ocr/pdf:
    post:
      operationId: create_upload_file_ocr_pdf_post
      parameters:
      - in: query
        name: force_ocr
        required: false
        schema:
          default: false
          title: Force Ocr
          type: boolean
      - in: query
        name: language
        required: false
        schema:
          title: Language
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_create_upload_file_ocr_pdf_post'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Create Upload File

